#!/bin/sh

#yarn encore prod --config-name configProd
rsync -avhp ./ u73511181@home471995587.1and1-data.host:~/gestion-projet --include=public/build --include=vendor --include=public/.htaccess --exclude-from=.gitignore --exclude=".*" 
ssh u73511181@home471995587.1and1-data.host 'cd ~/gestion-projet && /usr/bin/php7.1-cli bin/console cache:clear && exit'
#yarn encore dev --config-name configDev